### ISSUE TITLE
Bug with @summary, @todo, @classdesc, etc.

### ISSUE THREAD

**Issue by lambertsteven** [yavorskiy/comment-parser#19]
JSDoc has a few tags that allow space separated text as the description with no name. Tags such as [@summary](http://usejsdoc.org/tags-summary.html), [@todo](http://usejsdoc.org/tags-todo.html), and [@classdesc](http://usejsdoc.org/tags-classdesc.html) do this. When any of these are used, the parser assumes that the first word is the name of the tag, and the rest of the line is the description, which is incorrect.

For example.
```js
/**
 * @summary A concise summary.
 */
```

Gets parsed as 
```js
{
    "tags": [
      {
        "tag": "summary",
        "name": "A",
        "optional": false,
        "description": "concise summary.",
        "type": "",
        "line": 53,
        "source": "@summary A concise summary."
      }
}
```

What you would expect is this
```js
{
    "tags": [
      {
        "tag": "summary",
        "name": "",
        "optional": false,
        "description": "A concise summary.",
        "type": "",
        "line": 53,
        "source": "@summary A concise summary."
      }
}
```

**Comment by zxqfox** [comment]
This project is pretty generic, but logic for `@param`-like tags is hardcoded ;-(

It can be solved via custom parsers:
```js
var parser = require('comment-parser');
var PARSERS = parse.PARSERS;
parser(source, {parsers: [
  PARSERS.parse_tag,
  PARSERS.parse_type,
  // instead of PARSERS.parse_name:
  function (str, data) {
    if (data.tag === 'summary') { return null; }
    return PARSERS.parse_name.apply(this, arguments);
  },
  PARSERS.parse_description,
]});
```

But yeah, we can think about removing hardcode or introducing tag set to parse types/names.

**Comment by lambertsteven** [comment]
This is a really nice comment parser, I'd love to see it work with non `@param`-like tags.

The custom parsers is a nice workaround for now.

**Comment by yavorskiy** [comment]
@lambertsteven let me see what I can do

**Comment by zxqfox** [comment]
@lambertsteven @yavorskiy Any progress here? Do we really need this?

**Comment by yavorskiy** [comment]
You can blame me for being most irresponsible maintainer and I will agree, but still check [similar propblem/solution](https://github.com/yavorskiy/comment-parser/issues/21#issuecomment-142757706)

**Comment by lambertsteven** [comment]
The custom provided by @zxqfox worked for me. I will close this since the custom parser capabilities will work to fix future issues of this nature.
