### ISSUE TITLE
Feature request: Add option to not left trim comment spacing

### ISSUE THREAD

**Issue by lambertsteven** [yavorskiy/comment-parser#20]
I'd like to be able to keep the spacing in comments and tags so that I can parse the description and tags using something where spaces matter (like markdown, yaml, etc.). The `parse_block` function automatically trims the comment line and tag source, I'd like an option to just trim the right hand side of the comment line using:

```js
var RE_TRIM_RIGHT = /^[\n]+|[\s\uFEFF\xA0]+$/g;

// line 199
if (option)
  line.source = line.source.replace(RE_TRIM_RIGHT, '');

// line 213
if (option)
  tag.source = tag.source.join('\n').replace(RE_TRIM_RIGHT, '');
```

I can write up a pull request if your ok with the request. Just let me know what the flag should be and how you'd like it passed to the parser.

**Comment by ryanfitzer** [comment]
Also just ran into this need. Any thoughts on adding this as an option?

**Comment by zxqfox** [comment]
Since it's a parser, would be nice to preserve all original content by default. IMO.

**Comment by yavorskiy** [comment]
I am going to add `opts.preserve_space` with default value `false` to not break existing functionality. 
And have `if (!opts.preserve_space) { line.source = line.source.trim(); }` [here](https://github.com/yavorskiy/comment-parser/blob/master/index.js#L195)

Does it look fine?

**Comment by ryanfitzer** [comment]
Much appreciated!

**Comment by zxqfox** [comment]
LGTM, but... what about https://github.com/yavorskiy/comment-parser/blob/master/index.js#L8-L11 these spaces?

**Comment by yavorskiy** [comment]
@zxqfox  yeah, good point, those are clearing space on the left

**Comment by lambertsteven** [comment]
:+1:

**Comment by yavorskiy** [comment]
ok, so I tried to put something together, see [PR#13](https://github.com/yavorskiy/comment-parser/pull/23). It solves something [like this](https://github.com/yavorskiy/comment-parser/blob/preserve-indentation/tests/parse.spec.js#L135-L155), @ryanfitzer I hope you can suggest more test cases.

**Comment by ryanfitzer** [comment]
I'll take a look. In the interim, we've just been using a formatter to reformat the code examples.

Thanks for working on this.

**Comment by gajus** [comment]
Whats the latest?

**Comment by yavorskiy** [comment]
Refactored whitespace handling is master, will be published soon

**Comment by benoitjchevalier** [comment]
If anyone like me ended up here and couldn't find the option: it's `trim: false` on the option object, e.g:

```
parser.file(filePath, {trim: false}, (err, data) => {
   //do stuff
})
```
