### ISSUE TITLE
@return not parsing correctly

### ISSUE THREAD

**Issue by omerts** [yavorskiy/comment-parser#21]
Hello,

Tags that don't have a name, such as a @return tag, get parsed incorrectly. 
For example:
```javascript
   * @return {undefined}    Doesn't return anything
```
Gets parsed as:
```
 { tag: 'return',
   type: 'undefined',
   name: 'Doesn\'t',
   optional: false,
   description: '<p>return anything</p>',
   line: 3,
   source: '@return {undefined}   Doesn\'t return anything' }
```

**Comment by ryanfitzer** [comment]
Adding a custom parser for the `name` property allows the text after `{type}` to act as the `description`:

```js
var fs = require( 'fs' );
var parser = require( 'comment-parser' );
var PARSERS = parser.PARSERS;
var content = fs.readFileSync( './path/to/source.js', { encoding: 'utf8' } );

function parse_name_custom( str, data ) {
    
    // Use original `parse_name` if not `return` tag
    if ( data.tag !== 'return' ) {
        return PARSERS.parse_name( str, data );
    }
    
    // Set the text as the `description` property
    data.description = str;

    return {
        source: str,
        data: data
    };
}

var output = parser( content, {
    parsers: [
        PARSERS.parse_tag,
        PARSERS.parse_type,
        parse_name_custom,
        PARSERS.parse_description
    ]
});
```

**Comment by yavorskiy** [comment]
I know my answer is too late, but still. I've read through source code and tried to make changes to standard flow. Didn't get anything that would look fine and keep parser generic. Ended up with something very similar to what @ryanfitzer proposed. Would this work for you @omerts.

```js
function skip(parser, tag, stubData) {
  return function(str, data) {
    return data.tag === tag ? {
      source : '', 
      data   : data
    } : parser(str, data);
  };
}

parse(source, {
  parsers: [
    parse.PARSERS.parse_tag,
    skip(parse.PARSERS.parse_type, 'return'),
    skip(parse.PARSERS.parse_name, 'return'),
    parse.PARSERS.parse_description
  ]
});
```

I am going to close this issue if no objections

**Comment by ryanfitzer** [comment]
@yavorskiy Regarding `source : '',` in your `skip` function, I was under the impression that `str` is supposed to be returned. I guess I misunderstood things a bit.

Also, what is the idea behind `stubData`? I don't see it used anywhere.

**Comment by yavorskiy** [comment]
sorry, updated my snippet, was copypasting and mistakenly left `stubData` there. As for what parser is returning there is some notes in README "...returns null or {source: '', data:{}} where source is **consumed** substring and data is a payload with tag node fields." sorry if It wasn't explained well. So stubbed parser not consuming anything, i.e. leaving string untouched for next parser in chain

**Comment by omerts** [comment]
@yavorskiy  sorry for the late response, the above custom parser, causes the type to be part of the description, so the current output is:
```
{ tag: 'return',
  description: '{string} The description of the direction',
  optional: false,
  type: '',
  name: '',
  line: 4,
  source: '@return {string} The description of the direction',
  formattedDescription: '<p>{string} The description of the direction</p>' }
```

But I got the idea, I could work my way through, even though, imho @return should be natively supported.

**Comment by yavorskiy** [comment]
You are right, you can make a custom parsing rule and have it as flexible as you need. As for natively supported @return, idea was to build generic parser agnostic to actual tags

**Comment by yavorskiy** [comment]
@omerts You are right, you can make a custom parsing rule and have it as flexible as you need. As for natively supported `return`, idea was to build generic parser agnostic to actual tags
