### ISSUE TITLE
Does not parse comments that start text on the same line

### ISSUE THREAD

**Issue by daprahamian** [yavorskiy/comment-parser#22]
Currently, comment-parser does not recognize multi-line comments that have text on the first line. For example:

``` js
/** Starting comment on the same line
 *  Here is some more stuff
 */
```

JSDoc3 seems to handle these comments fine. Is there a reason why they are not parsed here?

**Comment by daprahamian** [comment]
Hi. Any update on this?

**Comment by pabigot** [comment]
+1.

It also won't recognize the comment if the closing `*/` is preceded by text:

    /** 
     * Start here
     * Here is more stuff */

**Comment by yavorskiy** [comment]
closing with [unit test](https://github.com/yavorskiy/comment-parser/blob/master/tests/parse.spec.js#L256) proving it works
