### ISSUE TITLE
Question: description parser does not parse $

### ISSUE THREAD

**Issue by straker** [yavorskiy/comment-parser#28]
Is there a specific reason why a description stops parsing at the `$` symbol?

``` js
// parser.js - PARSERS.parse_description
var result = str.match(/^\s+([^$]+)?/);
```

**Comment by kus** [comment]
+1 ran into this when I had @example with $

**Comment by zxcabs** [comment]
@straker @kus you can try use #30

**Comment by zxqfox** [comment]
@zxcabs I guess it should be `str.match(/^\s+([^\r\n]+)?/);`

**Comment by zxcabs** [comment]
@zxqfox no, test says that comment string for tag should be multiline
https://github.com/yavorskiy/comment-parser/blob/master/tests/parse.spec.js#L291

**Comment by straker** [comment]
I use `/^\s+([\s\S]+)?/` in my codebase of [livingcss](https://github.com/straker/livingcss/blob/master/lib/parseComments.js#L49) and it seems to work well for me.
