### ISSUE TITLE
 Will not process preserved comments

### ISSUE THREAD

**Issue by phun-ky** [yavorskiy/comment-parser#31]
Original issue posted here: https://github.com/straker/livingcss/issues/34

I'm creating a living styleguide from many stylus files, and each file is documented with JSDoc syntax (I am currently converting from documentcss to livingcss). The files are preprocessed and bundled into a bundle file containing all relevant documentation. To actually preserve the comments through the preprocessor, I am forced to use exclamation marks, `!`, to dictate which comments the preprocessor shall NOT remove. This results in livingcss (that depends on this module) not handling the JSDoc. Why?

To clarify, this works with livingcss:

    /**
     * My Section
     *
     * A description of the section and how to use it.
     *
     * @section
     */

This does not:

    /**!
     * My Section
     *
     * A description of the section and how to use it.
     *
     * @section
     */

**Comment by zxqfox** [comment]
But why should it be treated as JSDoc block comment?

**Comment by phun-ky** [comment]
Well, the issue  isn't that, because the stylus preprocessor is removing comments that is not marked with the exclamation mark. 


Sendt fra min Samsung Galaxy-smarttelefon.
-------- Opprinnelig melding --------Fra: Alexej Yaroshevich <notifications@github.com> Dato: 20.04.2017  21:11  (GMT+01:00) Til: yavorskiy/comment-parser <comment-parser@noreply.github.com> Ko: Alexander Vassbotn Røyne-Helgesen <alexander@phun-ky.net>, Author <author@noreply.github.com> Emne: Re: [yavorskiy/comment-parser] Will not process preserved comments (#31) 
But why should it be treated as JSDoc block comment?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/yavorskiy/comment-parser","title":"yavorskiy/comment-parser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/yavorskiy/comment-parser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zxqfox in #31: But why should it be treated as JSDoc block comment?"}],"action":{"name":"View Issue","url":"https://github.com/yavorskiy/comment-parser/issues/31#issuecomment-295863654"}}}

**Comment by yavorskiy** [comment]
This is way too outdated, but I am trying clean up issues log. I can't find mentions of `/**!` syntax in JSDoc [documentation](http://usejsdoc.org/about-getting-started.html), however standard `/***` approach for ignoring should work fine

> Comments beginning with `/*`, `/***`, or more than 3 stars will be ignored.
