### ISSUE TITLE
Bundle @types with comment-parser

### ISSUE THREAD

**Issue by jhm-ciberman** [yavorskiy/comment-parser#32]
Hello. It will be a good idea to bundle the Types .d.ts file with comment-parser for all the Typescript users.

This is the file I have created with the types for the comment-parser package. 

```typescript
// Type definitions for comment-parser 0.3.2
// Project: comment-parser
// Definitions by: Javier "Ciberman" Mora <https://github.com/jhm-ciberman/>

declare module "comment-parser" {
    interface Comment {
        tags: Tag[];
        line: number;
        description: string;
        source: string;
    }
    interface Tag {
        tag: string;
        name: string;
        optional: boolean;
        type: string;
        description: string;
        line: number;
        source: string;
    }
    interface Options {
        parsers?: [(str:string, data:any) => {source:string, data:any}];
        dotted_names?: boolean;
    }

    function parse(str: string, opts?:Options): [Comment];

    export = parse;
}

```

If you want to ship the types with your module and need assistance I can help you. 
Thanks. 

Instructions about @types can be found in: http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

**Comment by jhm-ciberman** [comment]
If you want to ship it with the module you may use this file instead:
`index.d.ts`
```
// Type definitions for comment-parser 0.3.2
// Project: comment-parser
// Definitions by: Javier "Ciberman" Mora <https://github.com/jhm-ciberman/>

declare interface CommentParser {
    interface Comment {
        tags: Tag[];
        line: number;
        description: string;
        source: string;
    }
    interface Tag {
        tag: string;
        name: string;
        optional: boolean;
        type: string;
        description: string;
        line: number;
        source: string;
    }
    interface Options {
        parsers?: [(str:string, data:any) => {source:string, data:any}];
        dotted_names?: boolean;
    }
}

declare function parse(str: string, opts?:CommentParser.Options): [CommentParser.Comment];

export = parse;
```

**Comment by yavorskiy** [comment]
@jhm-ciberman I know it's way too late but thanks a lot for your suggestion. I have tried to add your code, but my editor kept highlighting nested interface declarations with warnings. I wouldn't be surprised if my modifications are dump, please correct me with PR if you still willing to help. Thanks

**Comment by HamedFathi** [comment]
@jhm-ciberman @yavorskiy

How to pass a custom parser with this definition?

![image](https://user-images.githubusercontent.com/8418700/60356619-af0e7980-99e6-11e9-86b5-dd5ebbe50117.png)

I just pasted custom parsers sample in the read me and I got above error.
How to fix it?
