### ISSUE TITLE
Get the Method that belongs to the comment

### ISSUE THREAD

**Issue by ceemoo91** [yavorskiy/comment-parser#40]
Hello development team,

is there any possibility to get the method-name that belongs to a comment?

Example:
```javascript
/** function to login
   * @param {String} username
   * @param {String} password
   */
login(username, password){...}
```

i have an array with all function names and now i want to combine each function with the meta data from the comment

Best wishes
ceemoo91

**Comment by yavorskiy** [comment]
Unfortunately it is not possible. Parser is agnostic to the content outside of comment blocks
