### ISSUE TITLE
Callback Done

### ISSUE THREAD

**Issue by Snewkis** [yavorskiy/comment-parser#45]
Hello,

Is there a callback function when the parsing is done ?

**Comment by yavorskiy** [comment]
there is no callback, parser is synchronous since it's not using any async functions underneath. 

The only async flow is the file stream parser
> Also you can parse entire file with parse.file('path/to/file', callback) or acquire an instance of Transform stream with parse.stream().

**Comment by Snewkis** [comment]
Ok thanks :)
