### ISSUE TITLE
Consider loosening tag title 

### ISSUE THREAD

**Issue by brettz9** [yavorskiy/comment-parser#53]
While your [PARSERS.parse_tag](https://github.com/yavorskiy/comment-parser/blob/e8d4681073ca2563e77e517193deac4c8221075b/parsers.js#L13) is more liberal in allowing any non-whitespace, your [`parse_block` function](https://github.com/yavorskiy/comment-parser/blob/master/parser.js#L104)--called by the return function of `mkextract` and used by your `parse` public API--is more strict in insisting that what jsdoc calls a tag "title" and what you parse as "tag" begins with `\w`.

This seems to contradict the greater looseness of jsdoc itself, which merely requires `\S`: https://github.com/jsdoc/jsdoc/blob/aa0b6c1bfa3ab1aea10e579f9d6168fcb8ad5332/lib/jsdoc/doclet.js#L124

I'd suggest loosening the requirement here too so that you are using `\S` in both places, in a manner consistent with jsdoc. For example, while the following should create two tags:

```js
/**
 * @aTag
 * @-anotherTag {Type} name Singleline or multiline description text
text
 */
```

...the results, instead merge `-anotherTag` with the previous `aTag` one: https://runkit.com/brettz9/runkit-npm-comment-parser-tag-issue

It'd admittedly probably be pretty rare to have something like the above, but since jsdoc allows it, I thought I'd mention it.

I'm filing this in the course of trying to find out what a valid (custom) tag can be, and as such, I think that even if you keep the old way, I think it'd be worth quickly mentioning in the docs the original requirements and how yours differs.

**Comment by yavorskiy** [comment]
@brettz9 thanks for pointing out, good suggestion. Published

**Comment by brettz9** [comment]
Great, thanks!
